runtime: python37
entrypoint: gunicorn -b :$PORT --chdir ubyssey/ wsgi:application

automatic_scaling:
  target_cpu_utilization: .75

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /service-worker.js
  static_files: service-workers/service-worker.js
  upload: service-workers/service-worker.js
- url: .*
  script: auto
  secure: always

