version: "2.1"
services:

## Starts up mySQL server for ubyssey.ca and Dispatch
  db:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ubyssey
      MYSQL_USER: root
      MYSQL_PASSWORD: ubyssey
      MYSQL_DATABASE: ubyssey
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=ubyssey --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 20
    container_name: ubyssey_db

## Starts up static file watcher for ubyssey.ca
  gulp:
    build: .
    # use yarn here, npm has an error with binding binary for node-sass
    command: bash -c "cd ubyssey.ca/ubyssey/static && yarn install && gulp"
    volumes:
      - .:/ubyssey.ca
    container_name: ubyssey_gulp

## Starts up static file watcher for Dispatch platform
  yarn:
    build: .
    command: bash -c "cd ../dispatch/dispatch/static/manager && yarn install && yarn start"
    volumes:
       - ./dispatch/dispatch:/dispatch/dispatch
    container_name: ubyssey_yarn

## Starts up Django server for ubyssey.ca and Dispatch
  django:
    build: .
    command: bash -c "cd ubyssey.ca && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./dispatch/dispatch:/dispatch/dispatch
      - .:/ubyssey.ca
    volumes_from: 
      - gulp
      - yarn
    ports:
      - "8000:8000"
      - "4444:4444"
    depends_on:
      db:
        condition: service_healthy
    container_name: ubyssey-dev
    stdin_open: true
    tty: true


volumes:
  data: {}
